version: "3"

services:
  caddy:
    image: vyronfiee/caddy
    container_name: caddy
    restart: always
    network_mode: host
    # ports:
    #   - "8080:80"
    volumes:
      # caddy volumes
      - ./data:/data
      - ./config:/config
      - ./caddy:/etc/caddy
      - ./index.html:/srv/index.html
      # s6-overlay
      # - ./etc/services:/etc/services.d
